#!/bin/bash

# ==============================================================================
# Swarm Command Center - Single VM Deployment Bootstrapper
# ==============================================================================
# This script automatically prepares a fresh Debian/Ubuntu VM (e.g. on GCP/AWS),
# installs Docker & Docker Compose, configures the necessary environment variables,
# and deploys the entire Swarm architecture via docker-compose.
# ==============================================================================

set -e # Exit on error

# Colors for output
GREEN='\033[0;32m'
BLUE='\033[0;34m'
RED='\033[0;31m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo -e "${BLUE}====================================================${NC}"
echo -e "${BLUE}  Starting Swarm Command Center Deployment...${NC}"
echo -e "${BLUE}====================================================${NC}"

# 1. Check if running as root or with sudo privileges
if [ "$EUID" -ne 0 ]; then
  echo -e "${RED}[ERROR] Please run this script with sudo or as root.${NC}"
  exit 1
fi

# 2. OS Detection (Basic check for Debian/Ubuntu)
if [ -f /etc/os-release ]; then
    . /etc/os-release
    if [[ "$ID" != "ubuntu" && "$ID" != "debian" ]]; then
        echo -e "${YELLOW}[WARNING] This script is optimized for Ubuntu/Debian. Your OS ($ID) may not be fully supported, but we'll try to proceed.${NC}"
    else
        echo -e "${GREEN}[OK] OS Detected: $PRETTY_NAME${NC}"
    fi
else
    echo -e "${YELLOW}[WARNING] Could not detect OS. Proceeding with standard Debian/Ubuntu commands...${NC}"
fi

# 3. Check for Docker
if ! command -v docker &> /dev/null; then
    echo -e "${YELLOW}[INFO] Docker not found. Installing Docker...${NC}"

    # Update packages and install prerequisites
    apt-get update -y
    apt-get install -y ca-certificates curl gnupg lsb-release

    # Add Docker’s official GPG key
    mkdir -m 0755 -p /etc/apt/keyrings
    curl -fsSL https://download.docker.com/linux/$ID/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg

    # Set up the repository
    echo \
      "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/$ID \
      $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null

    # Install Docker Engine and Compose plugin
    apt-get update -y
    apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin

    echo -e "${GREEN}[OK] Docker installed successfully.${NC}"
else
    echo -e "${GREEN}[OK] Docker is already installed.${NC}"
fi

# Start and enable docker service
systemctl enable docker
systemctl start docker

# 4. Interactive Configuration
echo -e "\n${BLUE}--- Configuration ---${NC}"
echo -e "To ensure the Web UI can connect to the Relay Server, we need your VM's Public IP Address."

# Try to auto-detect public IP via external service
DETECTED_IP=$(curl -s -m 5 https://ifconfig.me || echo "")

if [ -n "$DETECTED_IP" ]; then
    read -p "Detected Public IP is $DETECTED_IP. Press [Enter] to use this, or type a different IP/Domain: " USER_IP
    if [ -z "$USER_IP" ]; then
        USER_IP=$DETECTED_IP
    fi
else
    read -p "Enter the Public IP or Domain Name of this VM (e.g., 203.0.113.50): " USER_IP
    if [ -z "$USER_IP" ]; then
        echo -e "${RED}[ERROR] Public IP is required to configure the UI. Aborting.${NC}"
        exit 1
    fi
fi

# Ensure it's prefixed with http:// if not a secure domain setup
if [[ $USER_IP != http* ]]; then
    FINAL_URL="http://${USER_IP}:3001"
else
    FINAL_URL="${USER_IP}:3001"
fi

echo -e "${GREEN}[OK] UI will be configured to connect to Relay at: $FINAL_URL${NC}"

# 5. Environment Variable Setup (.env generation)
echo -e "${YELLOW}[INFO] Generating .env file for docker-compose...${NC}"

cat <<EOF > .env
# Auto-generated by deploy_single_vm.sh
VITE_RELAY_URL=$FINAL_URL
PORT=3001
DB_TYPE=MONGODB
MONGODB_URI=mongodb://mongodb:27017/swarm_core
WORKER_SECRET=production_secret_key_change_me
EOF

echo -e "${GREEN}[OK] .env file created.${NC}"

# 6. Check docker-compose.yml modification (We use .env variable replacement)
# The docker-compose.yml must be configured to use ${VITE_RELAY_URL} instead of a hardcoded string.
# We will dynamically ensure the compose file uses the env variable.

if grep -q "VITE_RELAY_URL=" docker-compose.yml; then
    # Use sed to replace the hardcoded line with the variable interpolation
    sed -i 's/VITE_RELAY_URL=.*/VITE_RELAY_URL=${VITE_RELAY_URL}/g' docker-compose.yml
    echo -e "${GREEN}[OK] docker-compose.yml verified.${NC}"
else
    echo -e "${RED}[WARNING] Could not find VITE_RELAY_URL in docker-compose.yml. Proceeding anyway.${NC}"
fi

# 7. Deployment
echo -e "\n${BLUE}--- Deploying Swarm ---${NC}"
echo -e "Building containers and starting the architecture. This may take several minutes..."

# Using the modern 'docker compose' command (V2)
docker compose up -d --build

echo -e "\n${GREEN}====================================================${NC}"
echo -e "${GREEN}  🚀 DEPLOYMENT COMPLETE! 🚀${NC}"
echo -e "${GREEN}====================================================${NC}"
echo -e "You can now access the Command Center UI at:"
echo -e "  -->  ${YELLOW}http://${USER_IP}${NC}"
echo -e ""
echo -e "To view the logs of the Relay server, run:"
echo -e "  docker compose logs -f relay"
echo -e "===================================================="
