import React from 'react';
import { Settings2, Save } from 'lucide-react';
import { useAppleMusicStore } from '../../store/appleMusicStore';
import { SocketManager } from '../../worker/SocketManager';
import { MessageType } from '@swarm/shared';
import type { AppleMusicConfigSaveMessage } from '@swarm/shared';

export const AppleMusicConfigUI: React.FC = () => {
  const {
    mediaUserToken, setMediaUserToken,
    storefront, setStorefront,
    alacFix, setAlacFix,
    autoUpload, rcloneRemote,
    lrcFormat, setLrcFormat,
    lrcType, setLrcType,
    language, setLanguage,
    tagSortOrder, setTagSortOrder,
    saveLrcFile, setSaveLrcFile,
    saveArtistCover, setSaveArtistCover,
    useSongInfoForPlaylist, setUseSongInfoForPlaylist
  } = useAppleMusicStore();

  const handleSave = () => {
    const payload: AppleMusicConfigSaveMessage = {
      type: MessageType.APPLE_MUSIC_CONFIG_SAVE,
      timestamp: Date.now(),
      mediaUserToken,
      storefront,
      alacFix,
      autoUpload,
      rcloneRemote,
      lrcFormat,
      lrcType,
      language,
      tagSortOrder,
      saveLrcFile,
      saveArtistCover,
      useSongInfoForPlaylist
    };
    SocketManager.getInstance().emit(MessageType.APPLE_MUSIC_CONFIG_SAVE, payload);
    // Could add a toast notification here
  };

  return (
    <div className="w-full h-full flex flex-col items-center py-10 overflow-y-auto">
      <div className="w-full max-w-4xl px-6 space-y-6">

        <div className="flex items-center justify-between p-6 bg-black/40 border border-white/10 rounded-2xl backdrop-blur-sm">
            <div className="flex items-center gap-4">
                <div className="w-12 h-12 rounded-xl flex items-center justify-center shadow-lg bg-blue-500/20 text-blue-500 shadow-blue-500/20">
                    <Settings2 size={24} />
                </div>
                <div>
                    <h3 className="text-lg font-bold text-white">Engine Configuration Matrix</h3>
                    <p className="text-sm text-muted-foreground">Advanced Go Ripper settings mapped to <code className="text-xs bg-white/10 px-1 rounded">config.yaml</code></p>
                </div>
            </div>
            <button
              onClick={handleSave}
              className="flex items-center gap-2 px-5 py-2.5 bg-primary hover:bg-[#fa5e6e] text-white font-semibold rounded-xl shadow-[0_0_15px_rgba(250,36,60,0.3)] transition-all"
            >
                <Save size={18} /> Save Config
            </button>
        </div>

        <div className="p-8 bg-black/40 border border-white/10 rounded-2xl backdrop-blur-sm space-y-6">
            <h4 className="text-sm uppercase tracking-wider text-muted-foreground font-bold border-b border-white/10 pb-2">Authentication Tokens</h4>
            <div className="space-y-4">
                <div className="space-y-1">
                    <label className="text-xs text-muted-foreground ml-1">Media User Token <span className="text-[#FA243C]">*</span></label>
                    <input
                      type="text"
                      value={mediaUserToken}
                      onChange={(e) => setMediaUserToken(e.target.value)}
                      placeholder="Extract from browser cookies (media-user-token)"
                      className="w-full bg-black/50 border border-white/10 rounded-lg px-3 py-2 text-sm text-white focus:ring-1 focus:ring-primary outline-none font-mono"
                    />
                    <p className="text-[10px] text-muted-foreground ml-1">Required for high-resolution ALAC and real-time lyrics extraction.</p>
                </div>
                <div className="space-y-1">
                    <label className="text-xs text-muted-foreground ml-1">Authorization Token</label>
                    <input type="text" placeholder="Bearer ..." className="w-full bg-black/50 border border-white/10 rounded-lg px-3 py-2 text-sm text-white focus:ring-1 focus:ring-primary outline-none font-mono opacity-50" disabled />
                    <p className="text-[10px] text-muted-foreground ml-1">Auto-generated by Swarm backend during initialization.</p>
                </div>
            </div>

            <h4 className="text-sm uppercase tracking-wider text-muted-foreground font-bold border-b border-white/10 pb-2 mt-8">Advanced Parameters</h4>
            <div className="grid grid-cols-2 gap-6">
                 <div className="space-y-1">
                    <label className="text-xs text-muted-foreground ml-1">Storefront ID</label>
                    <input
                      type="text"
                      value={storefront}
                      onChange={(e) => setStorefront(e.target.value)}
                      className="w-full bg-black/50 border border-white/10 rounded-lg px-3 py-2 text-sm text-white focus:ring-1 focus:ring-primary outline-none font-mono"
                    />
                </div>
                <div className="space-y-1">
                    <label className="text-xs text-muted-foreground ml-1">Translation Language Code</label>
                    <input
                      type="text"
                      value={language}
                      onChange={(e) => setLanguage(e.target.value)}
                      placeholder="e.g. ko-KR"
                      className="w-full bg-black/50 border border-white/10 rounded-lg px-3 py-2 text-sm text-white focus:ring-1 focus:ring-primary outline-none font-mono"
                    />
                    <p className="text-[10px] text-muted-foreground ml-1">Used for TTML translation lyrics.</p>
                </div>

                <div className="space-y-1">
                    <label className="text-xs text-muted-foreground ml-1">LRC Format</label>
                    <select
                        value={lrcFormat}
                        onChange={(e) => setLrcFormat(e.target.value as 'lrc' | 'ttml')}
                        className="w-full bg-black/50 border border-white/10 rounded-lg px-3 py-2 text-sm text-white focus:ring-1 focus:ring-primary outline-none"
                    >
                        <option value="lrc">Standard LRC</option>
                        <option value="ttml">TTML (Word-by-word)</option>
                    </select>
                </div>
                <div className="space-y-1">
                    <label className="text-xs text-muted-foreground ml-1">LRC Type</label>
                    <select
                        value={lrcType}
                        onChange={(e) => setLrcType(e.target.value as 'lyrics' | 'syllable-lyrics')}
                        className="w-full bg-black/50 border border-white/10 rounded-lg px-3 py-2 text-sm text-white focus:ring-1 focus:ring-primary outline-none"
                    >
                        <option value="lyrics">Standard (lyrics)</option>
                        <option value="syllable-lyrics">Syllable (syllable-lyrics)</option>
                    </select>
                </div>

                <div className="space-y-1 flex items-center justify-between bg-white/5 p-3 rounded-lg border border-white/5">
                    <span className="text-sm text-white/90">Save LRC File</span>
                    <input
                      type="checkbox"
                      checked={saveLrcFile}
                      onChange={(e) => setSaveLrcFile(e.target.checked)}
                      className="accent-primary w-4 h-4"
                    />
                </div>

                <div className="space-y-1 flex items-center justify-between bg-white/5 p-3 rounded-lg border border-white/5">
                    <span className="text-sm text-white/90">Save Artist Cover</span>
                    <input
                      type="checkbox"
                      checked={saveArtistCover}
                      onChange={(e) => setSaveArtistCover(e.target.checked)}
                      className="accent-primary w-4 h-4"
                    />
                </div>

                <div className="space-y-1 flex items-center justify-between bg-white/5 p-3 rounded-lg border border-white/5">
                    <span className="text-sm text-white/90">Use SongInfo For Playlist</span>
                    <input
                      type="checkbox"
                      checked={useSongInfoForPlaylist}
                      onChange={(e) => setUseSongInfoForPlaylist(e.target.checked)}
                      className="accent-primary w-4 h-4"
                    />
                </div>

                <div className="space-y-1 flex items-center justify-between bg-white/5 p-3 rounded-lg border border-white/5">
                    <span className="text-sm text-white/90">Apply ALAC Fix Patch</span>
                    <input
                      type="checkbox"
                      checked={alacFix}
                      onChange={(e) => setAlacFix(e.target.checked)}
                      className="accent-primary w-4 h-4"
                    />
                </div>
                <div className="space-y-1 flex items-center justify-between bg-white/5 p-3 rounded-lg border border-white/5">
                    <span className="text-sm text-white/90">Force Tag Sort Order</span>
                    <input
                      type="checkbox"
                      checked={tagSortOrder}
                      onChange={(e) => setTagSortOrder(e.target.checked)}
                      className="accent-primary w-4 h-4"
                    />
                </div>
            </div>
        </div>

      </div>
    </div>
  );
};
