syntax = "proto3";

package swarm;

service SwarmNode {
  // A high-speed, client-to-server streaming RPC to pipe massive binary files
  // directly between ephemeral workers or to the Relay Server.
  rpc PipeData (stream DataChunk) returns (TransferStatus) {}

  // A high-speed, server-to-client streaming RPC for a firewalled worker
  // to connect to the Relay Server and pull data from an ongoing transfer.
  rpc ReceivePipe (ReceivePipeRequest) returns (stream DataChunk) {}
}

message ReceivePipeRequest {
  string transfer_id = 1;
}

message DataChunk {
  string transfer_id = 1;
  bytes content = 2;
  bool is_last = 3;
}

message TransferStatus {
  bool success = 1;
  string message = 2;
  int64 bytes_received = 3;
}
