export enum WorkerStatus {
  ONLINE = 'ONLINE',
  OFFLINE = 'OFFLINE',
  BUSY = 'BUSY',
  ERROR = 'ERROR'
}

export enum TaskType {
  DOWNLOAD = 'DOWNLOAD',
  UPLOAD = 'UPLOAD',
  SYNC = 'SYNC',
  SCAN = 'SCAN'
}

export enum MessageType {
  AUTH_REQUEST = 'AUTH_REQUEST',
  AUTH_RESPONSE = 'AUTH_RESPONSE',
  WORKER_STATUS_UPDATE = 'WORKER_STATUS_UPDATE',
  TASK_ASSIGNMENT = 'TASK_ASSIGNMENT',
  TASK_PROGRESS = 'TASK_PROGRESS',
  TASK_COMPLETE = 'TASK_COMPLETE',
  PING = 'PING',
  PONG = 'PONG',
  CHAT_MESSAGE = 'CHAT_MESSAGE',
  CHAT_TYPING = 'CHAT_TYPING',
  FILE_OFFER = 'FILE_OFFER',
  FILE_LIST_REQUEST = 'FILE_LIST_REQUEST',
  FILE_LIST_RESPONSE = 'FILE_LIST_RESPONSE',
  FLEET_STATE_UPDATE = 'FLEET_STATE_UPDATE',
  REMOTE_LIST_REQUEST = 'REMOTE_LIST_REQUEST',
  REMOTE_LIST_RESPONSE = 'REMOTE_LIST_RESPONSE',
  BATCH_TASK_REQUEST = 'BATCH_TASK_REQUEST',
  CHAT_MESSAGE_DELIVERED = 'CHAT_MESSAGE_DELIVERED',
  OFFLINE_FILE_UPLOAD_REQUEST = 'OFFLINE_FILE_UPLOAD_REQUEST',
  SDP_OFFER = 'SDP_OFFER',
  SDP_ANSWER = 'SDP_ANSWER',
  ICE_CANDIDATE = 'ICE_CANDIDATE',
  STREAM_REQUEST = 'STREAM_REQUEST',
  STREAM_METADATA = 'STREAM_METADATA',
  GRPC_DISCOVERY_REQUEST = 'GRPC_DISCOVERY_REQUEST',
  GRPC_DISCOVERY_RESPONSE = 'GRPC_DISCOVERY_RESPONSE',
  DB_STATE_REQUEST = 'DB_STATE_REQUEST',
  DB_ROUTE_SWITCH_REQUEST = 'DB_ROUTE_SWITCH_REQUEST',
  DB_STATE_UPDATE = 'DB_STATE_UPDATE',
  PUBLIC_KEY_ANNOUNCE = 'PUBLIC_KEY_ANNOUNCE',
  PUBLIC_KEY_REQUEST = 'PUBLIC_KEY_REQUEST',
  PUBLIC_KEY_RESPONSE = 'PUBLIC_KEY_RESPONSE'
}
